apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: default
type: Opaque
stringData:
  endpoint: "minio.minio.svc.cluster.local:9000"
  access_key: "CHANGE_ME"
  secret_key: "CHANGE_ME"
